version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./web:/app
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://username:passwd!@pg:5432
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  pg-data: