version: '3'

services:
  pg:
    image: postgres # use latest official postgres version
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdata
volumes:
  pg-data: