#version: '3'
#
#services:
#  pg:
#    image: postgres # use latest official postgres version
#    env_file:
#      - postgres.env # configure postgres
#    ports:
#      - 5432:5432
#    volumes:
#      - ./db-data/pg-data:/var/lib/postgresql/data/ # persist data even if container shuts down

version: "3"

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

volumes:
  pg-data: